// https://orm.drizzle.team/docs/column-types/sqlite
import { LogPayload, VrcLogEvent } from "@/generated/desktopapi/type";
import { sqliteTable, text, integer, real } from "drizzle-orm/sqlite-core";


// desktopアプリから取得したVRChatのログデータのテーブル
export const logs = sqliteTable("logs", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  // Hash generated by Rust to uniquely identify events (prevent duplicates)
  hash: integer("hash").notNull().unique(),
  // Unix timestamp in milliseconds (i64 in Rust)
  timestamp: integer("timestamp").notNull(),
  // Event type string (e.g., "WorldEnter", "PlayerJoin") for easy querying
  eventType: text("event_type").notNull(),
  // Store the full VrcLogEvent payload as JSON
  data: text("data", { mode: 'json' }).$type<VrcLogEvent>().notNull(),
});

export function convertToDBLog(payload: LogPayload): DBLog {
  return {
    hash: payload.hash,
    timestamp: payload.timestamp,
    // Extract the type string (e.g., "PlayerJoin", "WorldEnter")
    eventType: payload.event.type,
    // With { mode: 'json' } in Drizzle, you can pass the object directly
    data: payload.event,
  };
}

export type DBLog = typeof logs.$inferInsert;



